import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { cn } from "@/app/lib/utils";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex min-h-screen flex-col antialiased",
          montserrat.className,
        )}
      >
        <Navbar />
        <div className="relative mx-auto w-[min(100%,1200px)] p-4 md:py-10">
          {children}
        </div>
      </body>
    </html>
  );
}
